version: '2'

services:
  runner:
    image: python:3
    container_name: oc1-tp1-runner
    working_dir: /var/www/app
    command: bash -c 'python main.py'
    volumes:
      - ./:/var/www/app
  test:
    image: python:3
    container_name: oc1-tp1-runner
    working_dir: /var/www/app
    command: bash -c 'python test.py'
    volumes:
      - ./:/var/www/app
